"""create_orders_and_activity_logs

Revision ID: cf246483d0af
Revises:
Create Date: 2026-03-01 14:26:02.879363

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cf246483d0af"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orders",
        sa.Column("patient_first_name", sa.String(length=255), nullable=True),
        sa.Column("patient_last_name", sa.String(length=255), nullable=True),
        sa.Column("patient_dob", sa.Date(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("pending", "processing", "completed", name="orderstatus"),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("document_filename", sa.String(length=512), nullable=True),
        sa.Column("extracted_data", sa.JSON(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "activity_logs",
        sa.Column("method", sa.String(length=10), nullable=False),
        sa.Column("path", sa.String(length=2048), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=False),
        sa.Column("request_summary", sa.Text(), nullable=True),
        sa.Column("order_id", sa.Uuid(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_activity_logs_order_id"), "activity_logs", ["order_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_activity_logs_order_id"), table_name="activity_logs")
    op.drop_table("activity_logs")
    op.drop_table("orders")
    op.execute("DROP TYPE IF EXISTS orderstatus")
    # ### end Alembic commands ###
